// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SCILRunner.Model;

namespace SCILRunner.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20180619111809_dataPointInitial")]
    partial class dataPointInitial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.0-rtm-30799");

            modelBuilder.Entity("SCILRunner.Model.DataPoint", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<long>("MemoryUsage");

                    b.Property<long?>("ScanId");

                    b.Property<DateTime>("Timestamp");

                    b.HasKey("Id");

                    b.HasIndex("ScanId");

                    b.ToTable("DataPoint");
                });

            modelBuilder.Entity("SCILRunner.Model.Scan", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime?>("EndTime");

                    b.Property<string>("FilePath");

                    b.Property<bool>("Finished");

                    b.Property<string>("OutputPath");

                    b.Property<DateTime>("StartTime");

                    b.Property<int>("Status");

                    b.HasKey("Id");

                    b.ToTable("Scans");
                });

            modelBuilder.Entity("SCILRunner.Model.DataPoint", b =>
                {
                    b.HasOne("SCILRunner.Model.Scan")
                        .WithMany("Datapoint")
                        .HasForeignKey("ScanId");
                });
#pragma warning restore 612, 618
        }
    }
}
